# Generated by Django 4.1.2 on 2022-10-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacemodule',
            name='name',
        ),
    ]
