# Generated by Django 4.1.2 on 2022-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceModule', '0003_interfacemodule_modulelocked_interfacemodule_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceevaluation',
            name='answer',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='interfaceevaluation',
            name='qualification',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='interfaceevaluation',
            name='question',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='interfacemodule',
            name='moduleLocked',
            field=models.BooleanField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='interfacemodule',
            name='quantityMicroModules',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
