# Generated by Django 4.1.2 on 2022-10-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceModule', '0004_alter_interfaceevaluation_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dateBirt',
            new_name='dateBirth',
        ),
    ]
