# Generated by Django 4.1.2 on 2022-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceModule', '0005_rename_datebirt_person_datebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
