# Generated by Django 4.1.2 on 2022-10-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceModule', '0006_person_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacemodule',
            old_name='state',
            new_name='status',
        ),
    ]
