# Generated by Django 4.1.2 on 2022-10-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceModule', '0007_rename_state_interfacemodule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfaceevaluation',
            old_name='question',
            new_name='questions',
        ),
        migrations.RenameField(
            model_name='interfacemodule',
            old_name='quantityMicroModules',
            new_name='quantity_microModules',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='dateBirth',
            new_name='date_birth',
        ),
    ]
