# Generated by Django 4.1.2 on 2022-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_module_app', '0002_rename_interfaceevaluation_interface_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_module',
            name='quantity_microModules',
            field=models.IntegerField(),
        ),
    ]
