# Generated by Django 4.1.2 on 2022-10-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_module_app', '0003_alter_interface_module_quantity_micromodules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_module',
            name='moduleLocked',
            field=models.BooleanField(),
        ),
    ]
