# Generated by Django 4.1.2 on 2022-10-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_module_app', '0004_alter_interface_module_modulelocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface_module',
            name='moduleLocked',
        ),
    ]
