# Generated by Django 4.1.2 on 2022-10-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_module_app', '0005_remove_interface_module_modulelocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='progression',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='psdw',
            field=models.CharField(max_length=16, verbose_name='Password'),
        ),
    ]
