# Generated by Django 4.1.2 on 2022-10-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_module_app', '0006_alter_user_progression_alter_user_psdw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='progression',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=4, null=True),
        ),
    ]
