# Generated by Django 4.1.2 on 2022-10-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_module_app', '0007_alter_user_progression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user_interface_module', 'verbose_name_plural': 'users_interface'},
        ),
        migrations.AlterField(
            model_name='user',
            name='progression',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
