# Generated by Django 5.1 on 2024-10-01 09:57

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Micro_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('status', models.BooleanField()),
                ('progression', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Resultado total')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('progression', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity_microModules', models.IntegerField()),
                ('micro_modules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.micro_module')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Introduce pregunta')),
                ('max_resultado', models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Calificación máxima')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('psdw', models.CharField(max_length=16, verbose_name='Password')),
                ('country', models.CharField(max_length=30)),
                ('date_birth', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('progression', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user_interface_module',
                'verbose_name_plural': 'users_interface',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Basic_techniques',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/basic_techniques')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/concepts')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/glossary')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Mid_techniques',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/mid_techniques')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Options_panel',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/options_panel')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Side_panel',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/side_panel')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Top_panel',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/top_panel')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/workstation')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Interface_evaluation',
            fields=[
                ('evaluations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.evaluations')),
            ],
            options={
                'verbose_name': 'interface_module_evaluation',
            },
            bases=('base_app.evaluations',),
        ),
        migrations.CreateModel(
            name='Mastering_evaluation',
            fields=[
                ('evaluations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.evaluations')),
            ],
            options={
                'verbose_name': 'mastering_module_evaluation',
            },
            bases=('base_app.evaluations',),
        ),
        migrations.CreateModel(
            name='Mixture_evaluation',
            fields=[
                ('evaluations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.evaluations')),
            ],
            options={
                'verbose_name': 'mixture_module_evaluation',
            },
            bases=('base_app.evaluations',),
        ),
        migrations.CreateModel(
            name='Interface_module',
            fields=[
                ('modules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.modules')),
                ('images', models.ImageField(upload_to='interface_module')),
            ],
            options={
                'verbose_name': 'interface_module',
            },
            bases=('base_app.modules',),
        ),
        migrations.CreateModel(
            name='Mastering_module',
            fields=[
                ('modules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.modules')),
            ],
            options={
                'verbose_name': 'mastering_module',
            },
            bases=('base_app.modules',),
        ),
        migrations.CreateModel(
            name='Mixture_module',
            fields=[
                ('modules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.modules')),
            ],
            options={
                'verbose_name': 'mixture_module',
            },
            bases=('base_app.modules',),
        ),
        migrations.CreateModel(
            name='ElegirRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_elegir', models.TextField(verbose_name='Introduce una opción de respuesta')),
                ('correcta_elegir', models.BooleanField(default=False, verbose_name='¿Esta es la opción correcta?')),
                ('pregunta_elegir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='base_app.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Esta es la respuesta correcta?')),
                ('resultado', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Resultado')),
                ('evaluacion_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='base_app.evaluations')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.pregunta')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.elegirrespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pdw', models.CharField(max_length=16, verbose_name='Password')),
                ('user_logged', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.interface_module'),
        ),
        migrations.AddField(
            model_name='user',
            name='mastering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.mastering_module'),
        ),
        migrations.AddField(
            model_name='user',
            name='mixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.mixture_module'),
        ),
    ]
