# Generated by Django 4.1.2 on 2022-11-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('answer', models.CharField(blank=True, max_length=5)),
                ('questions', models.CharField(blank=True, max_length=5)),
                ('qualification', models.DecimalField(blank=True, decimal_places=3, max_digits=5)),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('number_attempts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('progression', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity_microModules', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('psdw', models.CharField(max_length=16, verbose_name='Password')),
                ('country', models.CharField(max_length=30)),
                ('date_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('progression', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'user_interface_module',
                'verbose_name_plural': 'users_interface',
            },
        ),
        migrations.CreateModel(
            name='Interface_evaluation',
            fields=[
                ('evaluations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.evaluations')),
            ],
            options={
                'verbose_name': 'interface_module_evaluation',
            },
            bases=('base_app.evaluations',),
        ),
        migrations.CreateModel(
            name='Interface_module',
            fields=[
                ('modules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.modules')),
                ('images', models.ImageField(upload_to='interface_module')),
            ],
            options={
                'verbose_name': 'interface_module',
            },
            bases=('base_app.modules',),
        ),
        migrations.CreateModel(
            name='Mastering_evaluation',
            fields=[
                ('evaluations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.evaluations')),
            ],
            options={
                'verbose_name': 'mastering_module_evaluation',
            },
            bases=('base_app.evaluations',),
        ),
        migrations.CreateModel(
            name='Mastering_module',
            fields=[
                ('modules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.modules')),
            ],
            options={
                'verbose_name': 'mastering_module',
            },
            bases=('base_app.modules',),
        ),
        migrations.CreateModel(
            name='Mixture_evaluation',
            fields=[
                ('evaluations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.evaluations')),
            ],
            options={
                'verbose_name': 'mixture_module_evaluation',
            },
            bases=('base_app.evaluations',),
        ),
        migrations.CreateModel(
            name='Mixture_module',
            fields=[
                ('modules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.modules')),
            ],
            options={
                'verbose_name': 'mixture_module',
            },
            bases=('base_app.modules',),
        ),
        migrations.AddField(
            model_name='modules',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user'),
        ),
    ]
