# Generated by Django 5.1 on 2024-09-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_techniques',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/basic_techniques')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/concepts')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/glossary')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Mid_techniques',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/mid_techniques')),
            ],
            bases=('base_app.micro_module',),
        ),
    ]
