# Generated by Django 4.1.2 on 2022-11-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='interfaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.interface_module'),
        ),
    ]
