# Generated by Django 4.1.2 on 2022-11-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_modules_users_user_interfaces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interfaces',
            new_name='interface',
        ),
        migrations.AddField(
            model_name='user',
            name='mastering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.mastering_module'),
        ),
        migrations.AddField(
            model_name='user',
            name='mixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.mixture_module'),
        ),
    ]
