# Generated by Django 4.1.2 on 2022-11-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_rename_interfaces_user_interface_user_mastering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Micro_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('status', models.BooleanField()),
                ('progression', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='qualification',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='modules',
            name='progression',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='progression',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Options_panel',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/options_panel')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Side_panel',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/side_panel')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Top_panel',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/top_panel')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('micro_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.micro_module')),
                ('images', models.ImageField(upload_to='micro_module/workstation')),
            ],
            bases=('base_app.micro_module',),
        ),
        migrations.AddField(
            model_name='modules',
            name='micro_modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.micro_module'),
        ),
    ]
