# Generated by Django 4.1.2 on 2022-11-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_micro_module_alter_evaluations_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_module',
            name='progression',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
