# Generated by Django 4.1.2 on 2022-11-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_micro_module_progression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pdw', models.CharField(max_length=16, verbose_name='Password')),
                ('user_logged', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.user')),
            ],
        ),
    ]
