# Generated by Django 4.1.2 on 2022-11-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
