# Generated by Django 4.1.2 on 2022-11-07 21:18

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_user_managers_user_last_login_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base_app.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
